/* © Copyright CERN, 2026. BSD-2-Clause.
 * Cross-implementation parity for the Java codec, driven by the same golden
 * vectors the Python codec is held to — generated by supernova's C++ encoder.
 * Plain main() (no test framework): exit 0 = pass. */
package ch.quasarnova.hypernova;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class GoldenTest {

    private static int checks = 0;
    private static int failures = 0;

    private static void check(boolean condition, String what) {
        checks++;
        if (!condition) {
            failures++;
            System.out.println("FAIL: " + what);
        }
    }

    private static byte[] fromHex(String hex) {
        byte[] out = new byte[hex.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
        }
        return out;
    }

    private static String toHex(byte[] data) {
        StringBuilder builder = new StringBuilder(data.length * 2);
        for (byte b : data) builder.append(String.format("%02x", b));
        return builder.toString();
    }

    public static void main(String[] arguments) throws Exception {
        Path vectors = Paths.get(arguments.length > 0 ? arguments[0] : "../../tests/golden/vectors.json");
        String json = new String(Files.readAllBytes(vectors));
        Pattern entry = Pattern.compile("\\{\"name\":\\s*\"([^\"]+)\",\\s*\"hex\":\\s*\"([0-9a-f]+)\"\\}");
        Matcher matcher = entry.matcher(json);
        Map<String, byte[]> golden = new LinkedHashMap<>();
        while (matcher.find()) golden.put(matcher.group(1), fromHex(matcher.group(2)));
        check(golden.size() == 4, "expected 4 golden vectors, got " + golden.size());

        // 1. every vector decodes, re-encodes byte-identically (Variant fields)
        for (Map.Entry<String, byte[]> vector : golden.entrySet()) {
            Wire.NetworkMessage message = Wire.decode(vector.getValue(), null, false);
            byte[] reencoded = Wire.encode(message, false, null);
            check(toHex(reencoded).equals(toHex(vector.getValue())),
                  vector.getKey() + ": Java encoder diverges from C++ encoder");
        }

        // 2. spot values from the C++-authored vectors
        Wire.NetworkMessage single = Wire.decode(golden.get("single_int32"), null, false);
        check(single.publisherId == 2234, "single_int32 publisher id");
        check(single.messages.get(0).dataSetWriterId == 62541, "single_int32 writer id");
        check(((Long) single.messages.get(0).fields.get(0).value) == 7L, "single_int32 value");

        Wire.NetworkMessage scalars = Wire.decode(golden.get("all_scalars"), null, false);
        List<Wire.FieldValue> fields = scalars.messages.get(0).fields;
        check(fields.get(1).value.equals(Boolean.TRUE), "all_scalars boolean");
        check(((Long) fields.get(8).value) == -9000000000000000000L, "all_scalars int64");
        check(fields.get(12).value.equals("supernova"), "all_scalars string");

        Wire.NetworkMessage utf8 = Wire.decode(golden.get("uint64_pid_utf8"), null, false);
        check(utf8.messages.get(0).fields.get(1).value.equals("boundary ✓ utf8"),
              "utf8 string survived");

        // 3. DataValue + arrays + signing round trip within Java
        Wire.NetworkMessage rich = new Wire.NetworkMessage();
        rich.publisherId = 42;
        rich.publisherIdType = 1;
        rich.writerGroupId = 100;
        rich.groupSequenceNumber = 5;
        Wire.DataSetMessage dsm = new Wire.DataSetMessage();
        dsm.dataSetWriterId = 1;
        dsm.sequenceNumber = 5;
        List<Object> samples = new ArrayList<>();
        samples.add(1.5); samples.add(-2.25);
        dsm.fields.add(new Wire.FieldValue(Wire.BuiltinType.DOUBLE, samples, Wire.STATUS_GOOD, 133774531200000000L));
        dsm.fields.add(new Wire.FieldValue(Wire.BuiltinType.STRING, "java", 0x80000000L, null));
        rich.messages.add(dsm);

        byte[] key = new byte[32];
        for (int i = 0; i < 32; i++) key[i] = (byte) i;
        byte[] signedWire = Wire.encode(rich, true, key);
        Wire.NetworkMessage back = Wire.decode(signedWire, key, true);
        check(Boolean.TRUE.equals(back.verified), "signature verified");
        check(back.messages.get(0).fields.get(0).isArray(), "array survived");
        check(back.messages.get(0).fields.get(0).value.equals(samples), "array values survived");
        check(!back.messages.get(0).fields.get(1).isGood(), "bad quality survived");
        check(back.messages.get(0).fields.get(1).value.equals("java"), "string survived");

        // 4. tampering detected
        signedWire[10] ^= 0x01;
        boolean rejected = false;
        try {
            Wire.decode(signedWire, key, true);
        } catch (Wire.WireException expected) {
            rejected = true;
        }
        check(rejected, "tampered signed frame must be rejected");

        // 5. registry lookup document parsing
        Registry.Coordinates coordinates = Registry.parse(
            "{\"name\": \"a/b\", \"address\": \"opc.udp://239.0.0.5:4840\"," +
            " \"publisherId\": 42, \"publisherIdType\": \"UINT16\"," +
            " \"writerGroupId\": 100, \"dataSetWriterId\": 1," +
            " \"fields\": [{\"name\": \"counter\", \"type\": \"INT32\"}," +
            " {\"name\": \"samples\", \"type\": \"DOUBLE[]\"}]}");
        check(coordinates.publisherId == 42 && coordinates.writerGroupId == 100,
              "lookup coordinates parsed");
        check(coordinates.fieldNames.equals(List.of("counter", "samples")),
              "lookup field names parsed");

        System.out.println(checks + " checks, " + failures + " failures");
        System.exit(failures == 0 ? 0 : 1);
    }

    private GoldenTest() { }
}
